-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 16:02:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema furry-meme
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `furry-meme` ;

-- -----------------------------------------------------
-- Schema furry-meme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `furry-meme` DEFAULT CHARACTER SET cp1251 ;
USE `furry-meme` ;

-- -----------------------------------------------------
-- Table `furry-meme`.`компании`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`компании` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`компании` (
  `id_компании` INT(11) NOT NULL AUTO_INCREMENT,
  `имя_компании` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_компании`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`отчётные_периоды`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`отчётные_периоды` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`отчётные_периоды` (
  `id_отчетного_периода` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NULL DEFAULT NULL,
  `год` YEAR(4) NOT NULL,
  `квартал` ENUM('Q1', 'Q2', 'Q3', 'Q4') NOT NULL,
  PRIMARY KEY (`id_отчетного_периода`),
  UNIQUE INDEX `unic_idx` (`год` ASC, `квартал` ASC, `company_id` ASC) VISIBLE,
  INDEX `comp_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `comp_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`дивиденты`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`дивиденты` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`дивиденты` (
  `id_дивидент` INT(11) NOT NULL AUTO_INCREMENT,
  `id_компании` INT(11) NOT NULL,
  `id_отчётного_периода` INT(11) NOT NULL,
  `процент_дивидента` DECIMAL(10,4) NOT NULL,
  `получатель` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_дивидент`),
  INDEX `компании_диведент_idx` (`id_компании` ASC) VISIBLE,
  INDEX `отчетный_период_idx` (`id_отчётного_периода` ASC) VISIBLE,
  CONSTRAINT `дивидент_отчётный_период`
    FOREIGN KEY (`id_отчётного_периода`)
    REFERENCES `furry-meme`.`отчётные_периоды` (`id_отчетного_периода`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `id_компании`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`исходные_данные`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`исходные_данные` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`исходные_данные` (
  `id_исходные_данные` INT(11) NOT NULL AUTO_INCREMENT,
  `id_компании` INT(11) NOT NULL,
  `id_отчетного_периода` INT(11) NOT NULL,
  `выручка_от_реализации` DECIMAL(10,4) NOT NULL,
  `активы` DECIMAL(10,4) NOT NULL,
  `собственный_капитал` DECIMAL(10,4) NOT NULL,
  `чистая_прибыль` DECIMAL(10,4) NOT NULL,
  `привлеченный_капитал` DECIMAL(10,4) NOT NULL,
  PRIMARY KEY (`id_исходные_данные`),
  INDEX `исходные_данные_компании_idx` (`id_компании` ASC) VISIBLE,
  INDEX `отчентый_период_idx` (`id_отчетного_периода` ASC) VISIBLE,
  CONSTRAINT `отчентый_период`
    FOREIGN KEY (`id_отчетного_периода`)
    REFERENCES `furry-meme`.`отчётные_периоды` (`id_отчетного_периода`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `исходные_данные_компании`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`кредиты`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`кредиты` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`кредиты` (
  `id_кредита` INT(11) NOT NULL AUTO_INCREMENT,
  `id_компании` INT(11) NOT NULL,
  `процент_кредита` DECIMAL(10,4) NOT NULL,
  `сумма_по_кредиту` DECIMAL(10,4) NOT NULL,
  `дата_взятия` DATE NOT NULL,
  `дата_выплаты` DATE NOT NULL,
  `кредитная_ставка` DECIMAL(10,4) NOT NULL,
  PRIMARY KEY (`id_кредита`),
  INDEX `кредит_компания_idx` (`id_компании` ASC) VISIBLE,
  CONSTRAINT `кредит_компания`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`roe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`roe` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`roe` (
  `id_ROE` INT(11) NOT NULL AUTO_INCREMENT,
  `id_компании` INT(11) NOT NULL,
  `id_исходных_данных` INT(11) NOT NULL,
  `id_кредита` INT(11) NOT NULL,
  `id_дивиденда` INT(11) NOT NULL,
  `ROE` DECIMAL(10,4) NULL DEFAULT NULL,
  `EBIT` DECIMAL(10,4) NOT NULL,
  `рентабельность_продаж` DECIMAL(10,4) NULL DEFAULT NULL,
  `RONA` DECIMAL(10,4) NULL DEFAULT NULL,
  `FL` DECIMAL(10,4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ROE`),
  INDEX `roe_компания_idx` (`id_компании` ASC) VISIBLE,
  INDEX `roe_исходные_данные_idx` (`id_исходных_данных` ASC) VISIBLE,
  INDEX `roe_кредиты_idx` (`id_кредита` ASC) VISIBLE,
  INDEX `roe_диведенты_idx` (`id_дивиденда` ASC) VISIBLE,
  CONSTRAINT `id_дивидента`
    FOREIGN KEY (`id_дивиденда`)
    REFERENCES `furry-meme`.`дивиденты` (`id_дивидент`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_исходных_данных_roe`
    FOREIGN KEY (`id_исходных_данных`)
    REFERENCES `furry-meme`.`исходные_данные` (`id_исходные_данные`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_компании_roe`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_кредита_roe`
    FOREIGN KEY (`id_кредита`)
    REFERENCES `furry-meme`.`кредиты` (`id_кредита`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`sg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`sg` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`sg` (
  `id_sg` INT(11) NOT NULL AUTO_INCREMENT,
  `id_исходных_данных` INT(11) NOT NULL,
  `id_ROE` INT(11) NOT NULL,
  `id_компании` INT(11) NOT NULL,
  `id_кредита` INT(11) NOT NULL,
  `id_диведента` INT(11) NOT NULL,
  `реинвестиционная_прибыль` DECIMAL(10,4) NOT NULL,
  `Коэффициент_реинвестирования` DECIMAL(10,4) NOT NULL,
  `SG` DECIMAL(10,4) NOT NULL,
  PRIMARY KEY (`id_sg`),
  INDEX `sg_исходные_данные_idx` (`id_исходных_данных` ASC) VISIBLE,
  INDEX `sg_ROE_idx` (`id_ROE` ASC) VISIBLE,
  INDEX `sg_компания_idx` (`id_компании` ASC) VISIBLE,
  INDEX `sg_кредиты_idx` (`id_кредита` ASC) VISIBLE,
  INDEX `sg_дивиденты_idx` (`id_диведента` ASC) VISIBLE,
  CONSTRAINT `sg_дивиденты`
    FOREIGN KEY (`id_диведента`)
    REFERENCES `furry-meme`.`дивиденты` (`id_дивидент`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sg_исходные_данные`
    FOREIGN KEY (`id_исходных_данных`)
    REFERENCES `furry-meme`.`исходные_данные` (`id_исходные_данные`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sg_компания`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sg_кредиты`
    FOREIGN KEY (`id_кредита`)
    REFERENCES `furry-meme`.`кредиты` (`id_кредита`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sg_ROE`
    FOREIGN KEY (`id_ROE`)
    REFERENCES `furry-meme`.`roe` (`id_ROE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`users` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`users` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `furry-meme`.`контактные_данные`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `furry-meme`.`контактные_данные` ;

CREATE TABLE IF NOT EXISTS `furry-meme`.`контактные_данные` (
  `id_контактных_данные` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `номер_телефона` INT(11) NOT NULL,
  `инфо` VARCHAR(255) NULL DEFAULT 'нет данных"',
  `id_компании` INT(11) NOT NULL,
  PRIMARY KEY (`id_контактных_данные`),
  INDEX `компания_телефон_idx` (`id_компании` ASC) VISIBLE,
  CONSTRAINT `компания_телефон`
    FOREIGN KEY (`id_компании`)
    REFERENCES `furry-meme`.`компании` (`id_компании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = cp1251;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
