package com.loneliness.server.controller;

public enum  CommandName {
    CREATE_USER, AUTHORISE_USER, DELETE_USER, RECEIVE_ALL_USERS,
    RECEIVE_USER, UPDATE_USER,RECEIVE_ALL_USERS_IN_LIMIT,

    CALCULATE_PROFITABILITY, CALCULATE_NET_ASSET_TURNOVER, CALCULATE_RONA,
    CALCULATE_FL, CALCULATE_ROE, CALCULATE_ALL_DIFFERENTIAL_INDICATORS,

    CREATE_DIFFERENTIAL_INDICATORS, DELETE_DIFFERENTIAL_INDICATORS, RECEIVE_ALL_DIFFERENTIAL_INDICATORS,
    RECEIVE_ALL_DIFFERENTIAL_INDICATORS_IN_LIMIT, RECEIVE_DIFFERENTIAL_INDICATORS, UPDATE_DIFFERENTIAL_INDICATORS,
}
