package com.loneliness.server.controller;

public enum  CommandName {
    CREATE_USER, AUTHORISE_USER, DELETE_USER, RECEIVE_ALL_USERS,
     RECEIVE_USER, UPDATE_USER,RECEIVE_ALL_USERS_IN_LIMIT,

    CALCULATE_PROFITABILITY, CALCULATE_NET_ASSET_TURNOVER, CALCULATE_RONA,
    CALCULATE_FL, CALCULATE_ROE
}
