package com.loneliness.client.controller;

public enum CommandName {
    CREATE_USER, AUTHORISE_USER, DELETE_USER, RECEIVE_ALL_USERS,
    RECEIVE_USER, UPDATE_USER,RECEIVE_ALL_USERS_IN_LIMIT, USER_DATA_VALIDATION,

    CREATE_DIFFERENTIAL_INDICATORS, DELETE_DIFFERENTIAL_INDICATORS, RECEIVE_ALL_DIFFERENTIAL_INDICATORS,
    RECEIVE_ALL_DIFFERENTIAL_INDICATORS_IN_LIMIT, RECEIVE_DIFFERENTIAL_INDICATORS, UPDATE_DIFFERENTIAL_INDICATORS,
    DIFFERENTIAL_INDICATORS_VALIDATION,

    INDEX_VALIDATION,
}
